<template>
  <BaseDialog header="Test Dialog"
              full-height
              width="700px"
  >
    <template #content>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec augue id leo molestie fringilla. Aenean et gravida turpis. Quisque diam purus, egestas ac neque et, aliquam scelerisque eros. Mauris nibh dui, pharetra quis eros nec, pharetra venenatis dui. Maecenas porta tristique interdum. Morbi ornare elementum lacus. Morbi venenatis ac mi nec molestie.

      Nulla scelerisque massa sit amet velit ornare eleifend. Praesent a ante dui. Aliquam lacinia malesuada pulvinar. Etiam in aliquet felis, nec congue magna. Etiam non urna convallis leo efficitur scelerisque. Vestibulum efficitur nunc massa, id lobortis libero scelerisque vitae. Nulla tempus dapibus est at sagittis. Proin rhoncus accumsan molestie. Aliquam erat volutpat. Curabitur a orci neque.

      Quisque et ipsum leo. Vivamus sed lacus nec enim pellentesque pellentesque quis interdum felis. Nulla ultrices erat nunc, non dignissim diam porttitor sed. Aliquam erat volutpat. Donec interdum sed urna et placerat. Nulla vitae nisi sodales, varius augue vitae, fermentum enim. Integer eget aliquam velit.

      Pellentesque aliquam in nisl id egestas. Aliquam ultricies massa dui, aliquet eleifend nibh interdum ut. Sed erat enim, pretium at bibendum at, mattis nec sapien. Sed consequat aliquam lacus sit amet pulvinar. Quisque euismod, urna sed dictum porttitor, nisl sapien convallis libero, quis convallis erat velit sit amet nibh. Cras cursus quam orci, non egestas turpis malesuada non. Nulla vitae sodales est. Praesent finibus augue in orci molestie pellentesque. Integer tincidunt porttitor elementum. Mauris et tristique tortor, sit amet venenatis lorem. Ut tristique sodales viverra. Quisque tempor velit vitae sem efficitur, viverra posuere tortor facilisis. Quisque vitae congue lacus, condimentum luctus risus.

      Aenean consectetur dolor vel est tincidunt, imperdiet porta neque faucibus. Praesent magna ligula, auctor in nunc in, porttitor hendrerit risus. Donec blandit augue sed massa dictum tincidunt. Nullam semper ultrices nulla in pellentesque. Nam posuere urna ipsum, ac posuere metus sollicitudin ac. Donec vehicula mi eu magna vulputate, a ornare erat facilisis. Maecenas euismod consequat eros, et volutpat eros hendrerit sit amet. Maecenas congue scelerisque ultrices. Pellentesque mi tellus, egestas non nulla scelerisque, porttitor euismod eros. Duis consectetur rhoncus tellus, sed consequat mi blandit ac. Proin at odio ut turpis vestibulum pharetra sed eu mi. Proin et dapibus tellus, et dignissim ligula. Donec semper tristique consectetur.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec augue id leo molestie fringilla. Aenean et gravida turpis. Quisque diam purus, egestas ac neque et, aliquam scelerisque eros. Mauris nibh dui, pharetra quis eros nec, pharetra venenatis dui. Maecenas porta tristique interdum. Morbi ornare elementum lacus. Morbi venenatis ac mi nec molestie.

      Nulla scelerisque massa sit amet velit ornare eleifend. Praesent a ante dui. Aliquam lacinia malesuada pulvinar. Etiam in aliquet felis, nec congue magna. Etiam non urna convallis leo efficitur scelerisque. Vestibulum efficitur nunc massa, id lobortis libero scelerisque vitae. Nulla tempus dapibus est at sagittis. Proin rhoncus accumsan molestie. Aliquam erat volutpat. Curabitur a orci neque.

      Quisque et ipsum leo. Vivamus sed lacus nec enim pellentesque pellentesque quis interdum felis. Nulla ultrices erat nunc, non dignissim diam porttitor sed. Aliquam erat volutpat. Donec interdum sed urna et placerat. Nulla vitae nisi sodales, varius augue vitae, fermentum enim. Integer eget aliquam velit.

      Pellentesque aliquam in nisl id egestas. Aliquam ultricies massa dui, aliquet eleifend nibh interdum ut. Sed erat enim, pretium at bibendum at, mattis nec sapien. Sed consequat aliquam lacus sit amet pulvinar. Quisque euismod, urna sed dictum porttitor, nisl sapien convallis libero, quis convallis erat velit sit amet nibh. Cras cursus quam orci, non egestas turpis malesuada non. Nulla vitae sodales est. Praesent finibus augue in orci molestie pellentesque. Integer tincidunt porttitor elementum. Mauris et tristique tortor, sit amet venenatis lorem. Ut tristique sodales viverra. Quisque tempor velit vitae sem efficitur, viverra posuere tortor facilisis. Quisque vitae congue lacus, condimentum luctus risus.

      Aenean consectetur dolor vel est tincidunt, imperdiet porta neque faucibus. Praesent magna ligula, auctor in nunc in, porttitor hendrerit risus. Donec blandit augue sed massa dictum tincidunt. Nullam semper ultrices nulla in pellentesque. Nam posuere urna ipsum, ac posuere metus sollicitudin ac. Donec vehicula mi eu magna vulputate, a ornare erat facilisis. Maecenas euismod consequat eros, et volutpat eros hendrerit sit amet. Maecenas congue scelerisque ultrices. Pellentesque mi tellus, egestas non nulla scelerisque, porttitor euismod eros. Duis consectetur rhoncus tellus, sed consequat mi blandit ac. Proin at odio ut turpis vestibulum pharetra sed eu mi. Proin et dapibus tellus, et dignissim ligula. Donec semper tristique consectetur.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec augue id leo molestie fringilla. Aenean et gravida turpis. Quisque diam purus, egestas ac neque et, aliquam scelerisque eros. Mauris nibh dui, pharetra quis eros nec, pharetra venenatis dui. Maecenas porta tristique interdum. Morbi ornare elementum lacus. Morbi venenatis ac mi nec molestie.

      Nulla scelerisque massa sit amet velit ornare eleifend. Praesent a ante dui. Aliquam lacinia malesuada pulvinar. Etiam in aliquet felis, nec congue magna. Etiam non urna convallis leo efficitur scelerisque. Vestibulum efficitur nunc massa, id lobortis libero scelerisque vitae. Nulla tempus dapibus est at sagittis. Proin rhoncus accumsan molestie. Aliquam erat volutpat. Curabitur a orci neque.

      Quisque et ipsum leo. Vivamus sed lacus nec enim pellentesque pellentesque quis interdum felis. Nulla ultrices erat nunc, non dignissim diam porttitor sed. Aliquam erat volutpat. Donec interdum sed urna et placerat. Nulla vitae nisi sodales, varius augue vitae, fermentum enim. Integer eget aliquam velit.

      Pellentesque aliquam in nisl id egestas. Aliquam ultricies massa dui, aliquet eleifend nibh interdum ut. Sed erat enim, pretium at bibendum at, mattis nec sapien. Sed consequat aliquam lacus sit amet pulvinar. Quisque euismod, urna sed dictum porttitor, nisl sapien convallis libero, quis convallis erat velit sit amet nibh. Cras cursus quam orci, non egestas turpis malesuada non. Nulla vitae sodales est. Praesent finibus augue in orci molestie pellentesque. Integer tincidunt porttitor elementum. Mauris et tristique tortor, sit amet venenatis lorem. Ut tristique sodales viverra. Quisque tempor velit vitae sem efficitur, viverra posuere tortor facilisis. Quisque vitae congue lacus, condimentum luctus risus.

      Aenean consectetur dolor vel est tincidunt, imperdiet porta neque faucibus. Praesent magna ligula, auctor in nunc in, porttitor hendrerit risus. Donec blandit augue sed massa dictum tincidunt. Nullam semper ultrices nulla in pellentesque. Nam posuere urna ipsum, ac posuere metus sollicitudin ac. Donec vehicula mi eu magna vulputate, a ornare erat facilisis. Maecenas euismod consequat eros, et volutpat eros hendrerit sit amet. Maecenas congue scelerisque ultrices. Pellentesque mi tellus, egestas non nulla scelerisque, porttitor euismod eros. Duis consectetur rhoncus tellus, sed consequat mi blandit ac. Proin at odio ut turpis vestibulum pharetra sed eu mi. Proin et dapibus tellus, et dignissim ligula. Donec semper tristique consectetur.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec augue id leo molestie fringilla. Aenean et gravida turpis. Quisque diam purus, egestas ac neque et, aliquam scelerisque eros. Mauris nibh dui, pharetra quis eros nec, pharetra venenatis dui. Maecenas porta tristique interdum. Morbi ornare elementum lacus. Morbi venenatis ac mi nec molestie.

      Nulla scelerisque massa sit amet velit ornare eleifend. Praesent a ante dui. Aliquam lacinia malesuada pulvinar. Etiam in aliquet felis, nec congue magna. Etiam non urna convallis leo efficitur scelerisque. Vestibulum efficitur nunc massa, id lobortis libero scelerisque vitae. Nulla tempus dapibus est at sagittis. Proin rhoncus accumsan molestie. Aliquam erat volutpat. Curabitur a orci neque.

      Quisque et ipsum leo. Vivamus sed lacus nec enim pellentesque pellentesque quis interdum felis. Nulla ultrices erat nunc, non dignissim diam porttitor sed. Aliquam erat volutpat. Donec interdum sed urna et placerat. Nulla vitae nisi sodales, varius augue vitae, fermentum enim. Integer eget aliquam velit.

      Pellentesque aliquam in nisl id egestas. Aliquam ultricies massa dui, aliquet eleifend nibh interdum ut. Sed erat enim, pretium at bibendum at, mattis nec sapien. Sed consequat aliquam lacus sit amet pulvinar. Quisque euismod, urna sed dictum porttitor, nisl sapien convallis libero, quis convallis erat velit sit amet nibh. Cras cursus quam orci, non egestas turpis malesuada non. Nulla vitae sodales est. Praesent finibus augue in orci molestie pellentesque. Integer tincidunt porttitor elementum. Mauris et tristique tortor, sit amet venenatis lorem. Ut tristique sodales viverra. Quisque tempor velit vitae sem efficitur, viverra posuere tortor facilisis. Quisque vitae congue lacus, condimentum luctus risus.

      Aenean consectetur dolor vel est tincidunt, imperdiet porta neque faucibus. Praesent magna ligula, auctor in nunc in, porttitor hendrerit risus. Donec blandit augue sed massa dictum tincidunt. Nullam semper ultrices nulla in pellentesque. Nam posuere urna ipsum, ac posuere metus sollicitudin ac. Donec vehicula mi eu magna vulputate, a ornare erat facilisis. Maecenas euismod consequat eros, et volutpat eros hendrerit sit amet. Maecenas congue scelerisque ultrices. Pellentesque mi tellus, egestas non nulla scelerisque, porttitor euismod eros. Duis consectetur rhoncus tellus, sed consequat mi blandit ac. Proin at odio ut turpis vestibulum pharetra sed eu mi. Proin et dapibus tellus, et dignissim ligula. Donec semper tristique consectetur.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec augue id leo molestie fringilla. Aenean et gravida turpis. Quisque diam purus, egestas ac neque et, aliquam scelerisque eros. Mauris nibh dui, pharetra quis eros nec, pharetra venenatis dui. Maecenas porta tristique interdum. Morbi ornare elementum lacus. Morbi venenatis ac mi nec molestie.

      Nulla scelerisque massa sit amet velit ornare eleifend. Praesent a ante dui. Aliquam lacinia malesuada pulvinar. Etiam in aliquet felis, nec congue magna. Etiam non urna convallis leo efficitur scelerisque. Vestibulum efficitur nunc massa, id lobortis libero scelerisque vitae. Nulla tempus dapibus est at sagittis. Proin rhoncus accumsan molestie. Aliquam erat volutpat. Curabitur a orci neque.

      Quisque et ipsum leo. Vivamus sed lacus nec enim pellentesque pellentesque quis interdum felis. Nulla ultrices erat nunc, non dignissim diam porttitor sed. Aliquam erat volutpat. Donec interdum sed urna et placerat. Nulla vitae nisi sodales, varius augue vitae, fermentum enim. Integer eget aliquam velit.

      Pellentesque aliquam in nisl id egestas. Aliquam ultricies massa dui, aliquet eleifend nibh interdum ut. Sed erat enim, pretium at bibendum at, mattis nec sapien. Sed consequat aliquam lacus sit amet pulvinar. Quisque euismod, urna sed dictum porttitor, nisl sapien convallis libero, quis convallis erat velit sit amet nibh. Cras cursus quam orci, non egestas turpis malesuada non. Nulla vitae sodales est. Praesent finibus augue in orci molestie pellentesque. Integer tincidunt porttitor elementum. Mauris et tristique tortor, sit amet venenatis lorem. Ut tristique sodales viverra. Quisque tempor velit vitae sem efficitur, viverra posuere tortor facilisis. Quisque vitae congue lacus, condimentum luctus risus.

      Aenean consectetur dolor vel est tincidunt, imperdiet porta neque faucibus. Praesent magna ligula, auctor in nunc in, porttitor hendrerit risus. Donec blandit augue sed massa dictum tincidunt. Nullam semper ultrices nulla in pellentesque. Nam posuere urna ipsum, ac posuere metus sollicitudin ac. Donec vehicula mi eu magna vulputate, a ornare erat facilisis. Maecenas euismod consequat eros, et volutpat eros hendrerit sit amet. Maecenas congue scelerisque ultrices. Pellentesque mi tellus, egestas non nulla scelerisque, porttitor euismod eros. Duis consectetur rhoncus tellus, sed consequat mi blandit ac. Proin at odio ut turpis vestibulum pharetra sed eu mi. Proin et dapibus tellus, et dignissim ligula. Donec semper tristique consectetur.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec augue id leo molestie fringilla. Aenean et gravida turpis. Quisque diam purus, egestas ac neque et, aliquam scelerisque eros. Mauris nibh dui, pharetra quis eros nec, pharetra venenatis dui. Maecenas porta tristique interdum. Morbi ornare elementum lacus. Morbi venenatis ac mi nec molestie.

      Nulla scelerisque massa sit amet velit ornare eleifend. Praesent a ante dui. Aliquam lacinia malesuada pulvinar. Etiam in aliquet felis, nec congue magna. Etiam non urna convallis leo efficitur scelerisque. Vestibulum efficitur nunc massa, id lobortis libero scelerisque vitae. Nulla tempus dapibus est at sagittis. Proin rhoncus accumsan molestie. Aliquam erat volutpat. Curabitur a orci neque.

      Quisque et ipsum leo. Vivamus sed lacus nec enim pellentesque pellentesque quis interdum felis. Nulla ultrices erat nunc, non dignissim diam porttitor sed. Aliquam erat volutpat. Donec interdum sed urna et placerat. Nulla vitae nisi sodales, varius augue vitae, fermentum enim. Integer eget aliquam velit.

      Pellentesque aliquam in nisl id egestas. Aliquam ultricies massa dui, aliquet eleifend nibh interdum ut. Sed erat enim, pretium at bibendum at, mattis nec sapien. Sed consequat aliquam lacus sit amet pulvinar. Quisque euismod, urna sed dictum porttitor, nisl sapien convallis libero, quis convallis erat velit sit amet nibh. Cras cursus quam orci, non egestas turpis malesuada non. Nulla vitae sodales est. Praesent finibus augue in orci molestie pellentesque. Integer tincidunt porttitor elementum. Mauris et tristique tortor, sit amet venenatis lorem. Ut tristique sodales viverra. Quisque tempor velit vitae sem efficitur, viverra posuere tortor facilisis. Quisque vitae congue lacus, condimentum luctus risus.

      Aenean consectetur dolor vel est tincidunt, imperdiet porta neque faucibus. Praesent magna ligula, auctor in nunc in, porttitor hendrerit risus. Donec blandit augue sed massa dictum tincidunt. Nullam semper ultrices nulla in pellentesque. Nam posuere urna ipsum, ac posuere metus sollicitudin ac. Donec vehicula mi eu magna vulputate, a ornare erat facilisis. Maecenas euismod consequat eros, et volutpat eros hendrerit sit amet. Maecenas congue scelerisque ultrices. Pellentesque mi tellus, egestas non nulla scelerisque, porttitor euismod eros. Duis consectetur rhoncus tellus, sed consequat mi blandit ac. Proin at odio ut turpis vestibulum pharetra sed eu mi. Proin et dapibus tellus, et dignissim ligula. Donec semper tristique consectetur.
    </template>
  </BaseDialog>
</template>

<script setup>

import BaseDialog from "../../components/BaseDialog.vue";
</script>

<style scoped>

</style>